export const ECONOMIC_WEIGHTS = {
  AGE_VAR: 2.0,
  SEM_PENALTY: 2.0,
  ATT_VAR: 2.0,
  GENDER_PENALTY: 2.5,
  REUNION_RECENT: 2,
  REUNION_LAST: 0.1,
  REQUEST_REWARD: 100,
  ATT_VAR_THRESHOLD: 0.1,
  ATT_VAR_EPSILON: 0.01,
  REUNION_RECENT_THRESHOLD: 2,
  GENDER_ERROR_THRESHOLD: 0.01,
  GENDER_ERROR_EPSILON: 0.01,
  DEFAULT_STUDENT_YEAR: '25',
  SEM_TARGET_COUNT: 1
};
